Before starting with vector calculation in numpy lets understand about list

In [1]:
list = [1,2,3,4,56]

In [2]:
list[2]

3

In [5]:
list1 = [(1,2,3,),2,4,5,6,[2,4,7,6,5]]

In [6]:
list1[-1]

[2, 4, 7, 6, 5]

In [7]:
vector = [[1,2,3],[3,4,6],[4,6,7]]
print(vector)
print(type(vector))

[[1, 2, 3], [3, 4, 6], [4, 6, 7]]
<class 'list'>


In [8]:
vector1 = [[2,4,5],[4,6,7],[5,7,9]]
print(vector + vector1)

[[1, 2, 3], [3, 4, 6], [4, 6, 7], [2, 4, 5], [4, 6, 7], [5, 7, 9]]


In [ ]:
"""
To try the examples in the browser:
1. Type code in the input cell and press   Shift + Enter to execute
2. Or copy paste the code, and click on   the "Run" button in the toolbar
"""

In [9]:
# The standard way to import NumPy:
import numpy as np
#numpy is one of popular module for vector calculations

In [10]:
# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [11]:

x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [12]:
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.41914238,  0.63943171,  0.72960711, ..., -1.45697131,
        0.02345741,  1.20998529])

In [ ]:
a = np.arange(6)
a2 = a[np.newaxis, :]
print(a2.shape)
print(a)
print(a2)

In [19]:
a = np.array([[10,15]])
b = np.array([[20,9]])
print(a)
print(b)


[[10 15]]
[[20  9]]


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(a[0])

[1 2 3 4]


In [17]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
#addition of two vectors
a + b

array([[30, 24]])

In [21]:
a.T + b.T

array([[30],
       [24]])

In [22]:
(a + b).T

array([[30],
       [24]])

In [23]:
# Substraction of 2 vectors
a-b

array([[-10,   6]])

In [24]:
(a-b).T

array([[-10],
       [  6]])

In [25]:
(a-b).T == a.T - b.T

array([[ True],
       [ True]])

In [26]:
# Scaler Multiplication
a= 2
u = np.array([[30,15]])
(a * u).T

array([[60],
       [30]])

In [27]:
# Dot product of 2 Vectors
# for 2-D vectors, it is the equivalent to matrix multiplication

u = np.array([10,20])
v = np.array([25,6])

print(10 * 25 + 20 * 6)

np.dot(u,v)

370


370

In [28]:
# Matrix Addition

a = np.array([[12,10],[4,6],[40,31]])
b = np.array([[2,8],[46,63],[50,10]])

print(a)

[[12 10]
 [ 4  6]
 [40 31]]


In [29]:
print(b)

[[ 2  8]
 [46 63]
 [50 10]]


In [30]:
print(a, end=' =a\n')
print(b, end =' = b\n')

[[12 10]
 [ 4  6]
 [40 31]] =a
[[ 2  8]
 [46 63]
 [50 10]] = b


In [31]:
a + b

array([[14, 18],
       [50, 69],
       [90, 41]])

In [32]:
# Matrix Sustraction
a - b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

In [33]:
# Matrix scalar multiplication 

a = 4
b = np.array([[2,5],[3,7],[8,6]])

a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [34]:
# Matrix and vactor multiplication

a = [[5,10],[15,20]]
b =[10,12]

np.dot(a,b)

array([170, 390])

In [35]:
# Matrix to matrix multiplication
a = [[5,10],[15,20],[25,30]]
b = [[3,6],[9,5]]

np.dot(a,b)

array([[105,  80],
       [225, 190],
       [345, 300]])

In [39]:
a = [[2,3],[5,6],[4,6]]
print(type(a))
print(a+b)


<class 'list'>
[[2, 3], [5, 6], [4, 6], [3, 6], [9, 5]]


In [40]:
# transpose a matrix

a = np.array([[5,10],[15,20],[25,30]])
print(a,end='  = a\n')
print(a.T, end= '  =aT')

[[ 5 10]
 [15 20]
 [25 30]]  = a
[[ 5 15 25]
 [10 20 30]]  =aT

In [41]:
# create an Identity matrix
''' Identity matrix is the matrix
having all the diagonal elements are 
identical 
'''
I1 = np.eye(2)
I2 = np.eye(3)
print(I1, end ='  =I1\n' )
print(I2, end ='  =I2\n')

[[1. 0.]
 [0. 1.]]  =I1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]  =I2


In [42]:
# Inverse a matrix Given a square matrix a , return a matrix ainv satisfying
#dot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).
a = np.array([
    [2,1,0],
    [0,1,0],
    [1,2,1],
])
print(a, end= '= a\n')
print(np.linalg.inv(a), end='  =  |a|')

[[2 1 0]
 [0 1 0]
 [1 2 1]]= a
[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]]  =  |a|